IMAGE_NAME ?= sqlitebrowser
CONTAINER_NAME ?= sqlitebrowser
CONTAINER_HOSTNAME ?= sqlitebrowser
# Empty CMD = use the container default entry point
CMD=
PORTMAPS=-p 3001:3000

include ../Makefile_common
